### ISSUE TITLE
🚀 [feature] Chat GPT 관련 구현

### ISSUE THREAD

**Issue by Lee-Yeonjoo** [FoodZero/SM-project-BE#19]
# 🤖 기능 개요

레시피 추천 기능을 위한 챗 지피티 학습 구현

## ✅ Todo
- [x] gpt api 구현
- [x] 환경변수 코드 변경
- [x] api key 변경 - 결제카드 받고 결제 후 진행
- [x] 기획에 맞게 구현

### 📚 Remarks

**Additional context**
