### ISSUE TITLE
🚀 [feature] 엔티티 클래스 생성 및 회원가입 관련 api 구현

### ISSUE THREAD

**Issue by Lee-Yeonjoo** [FoodZero/SM-project-BE#3]
# 🤖 기능 개요
erd를 토대로 엔티티 클래스를 생성하고, 회원가입 기능을 구현할 것입니다.

## ✅ Todo
- [x] MemberPassword 엔티티 클래스 생성
- [x] 회원가입 api 구현
- [x] 이메일 찾기 api 구현
- [x] 문자 인증 전송 api
- [x] 회원가입 api에 문자 인증 검사 코드 추가
- [x] 비밀번호 찾기 - 인증메일 전송 api
- [x] 비밀번호 재설정 api
- [x] 닉네임 중복 확인 api
- [x] 이메일 찾기 - 문자인증코드 검증 추가

### 📚 Remarks

와이어 프레임 완성되면 기능에 맞게 수정 필요.
