### ISSUE TITLE
🚀 [feature] swagger, spring security 설정

### ISSUE THREAD

**Issue by hyoungj00n** [FoodZero/SM-project-BE#4]
# 🤖 기능 개요
swagger와 spring security 설정

## ✅ Todo
- [ ] swagger config 작성
- [ ] spring security config 작성
- [ ] redis 설정 파일 작성
- [ ] 응답 통일 코드 작성
